version: '3.8'

services:
  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - default
    entrypoint: ["/bin/sh", "-c", "/migrate && /auth"]

  postgres:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./auth/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres:

networks:
  default:
    driver: bridge
