services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./app/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres:

networks:
  default:
    driver: bridge
